name: Dev

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: build and test
        if: matrix.os != 'ubuntu-24.04'
        run: |
          cargo build --release --verbose --all
          cargo test --release --verbose --all
      - name: build and test
        if: matrix.os == 'ubuntu-24.04'
        run: |
          cargo build --release --verbose --all --exclude app
          cargo test --release --verbose --all --exclude app
